/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.es2.sistemaprisional.model.view;

import com.es2.sistemaprisional.controller.DiretorController;
import com.es2.sistemaprisional.controller.PresidioController;
import com.es2.sistemaprisional.model.FuncionarioCargos;
import com.es2.sistemaprisional.model.Presidio;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ranoc
 */
public class DiretorView extends javax.swing.JFrame {
    private Presidio presidio;
    private PresidioController presidioCtrl;
    private DiretorController diretorCtrl;
    
    /**
     * Creates new form DiretorView
     */
    public DiretorView(Presidio presidio) throws Exception {
        this.presidio = presidio;
        presidioCtrl = new PresidioController(presidio);
        diretorCtrl = new DiretorController(2);
        System.out.println(diretorCtrl.aposentarFuncionario(1));
        System.out.println(diretorCtrl.cadastrarCela(5, "setor 2"));
        System.out.println(diretorCtrl.cadastrarFuncionario(30,
                "José", 
                "123456788",
                "email@emaill.com", 
                FuncionarioCargos.FUNCIONARIO, 
                0));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param presidio é o presídio inicial carregado pelo sistema de arquivos
     */
    public static void main(Presidio presidio) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiretorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiretorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiretorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiretorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new DiretorView(presidio).setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(DiretorView.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
